name: Generate solved table

permissions:
  contents: write

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate table
        run: |
          python -m pip install --upgrade pip
          python tools/gen_solved_table.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update solved table and badges"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: |
            README.md
            docs/badges/*.json
          token: ${{ secrets.GITHUB_TOKEN }}
